### ISSUE TITLE
Margin curious behavior

### ISSUE THREAD

**Issue by o-k-harmash** [o-k-harmash/qr-code-component#1]
🤔 Curious CSS Behavior

The code

```css
  .container {
    width: 348px;
    margin: auto;
    padding: 28px;
    align-self: center;
  }
```

Have extra rule "align-self: center;", that not affected at all and crushed positioning when view height less then .container height.

I don’t know exactly why, but

```css
  .container{
      margin: auto;
  }
```
fixed the vertical shift when the screen height was smaller than the .card height. It actually worked better than using justify-content in that particular case.

rather then 

```css
  .container {
    align-self: center;
  }
```
on parent flex element.

It might be related to how margin: auto interacts with block layout and available space, especially when an element exceeds the viewport height — while justify-content relies on flex context, which may behave differently when the container isn’t filling the whole screen or lacks a height constraint.
